# -*- coding: utf-8 -*-
"""6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adRYZeaMfcSYNnFeV8zmBucBBmhE7-EK
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import *
import plotly.express as px
import numpy as np

# %matplotlib inline

path_mean = '/content/drive/MyDrive/Colab Notebooks/Karpov/lesson_6/avocado_mean.csv'
path_full = '/content/drive/MyDrive/Colab Notebooks/Karpov/lesson_6/avocado_full.csv'

avocado_mean = pd.read_csv(path_mean, index_col=0, squeeze=False, parse_dates=['Date'])
avocado_full = pd.read_csv(path_full, index_col=0, squeeze=False, parse_dates=['Date'])

AveragePrice = avocado_mean.rolling(50).mean()
AveragePrice.plot()

avocado_ewm = avocado_mean.ewm(span=2).mean()

avocado_ewm.plot()

avocado_full

organic_chicago = avocado_full.query('type == "organic" and region == "Chicago"')

ax_roll = organic_chicago.AveragePrice.rolling(4).mean()
ax_exp  = organic_chicago.AveragePrice.ewm(span=4).mean()

ax_exp = pd.DataFrame(ax_exp)
ax_roll = pd.DataFrame(ax_roll)
ax_exp

sns.set(
    font_scale=1,
    style="whitegrid",
    rc={'figure.figsize':(12,6)}
        )

sns.lineplot(data=ax_roll, color='red')
sns.lineplot(data=ax_exp)

# px.line(ax_exp, x=ax_exp.index, y='AveragePrice')
px.line(ax_roll, x=ax_roll.index, y='AveragePrice')

# 💀 Сложное задание! 💀

# Далее будем работать с данными по опозданиям в заключении сделок!

# В файле находится информация о том какие компании с кем и на какую сумму заключали сделки, а самое важное – насколько они при этом опоздали. Пример сабсэта данных:

# client_id	company_id	delay	revenue
# 0	2389	4240	-1 days -14:57:48.000000000	705436
# 1	7614	9544	-4 days -02:14:23.000000000	859266
# 2	2052	2427	-0 days -06:08:57.000000000	812416
# 3	9635	8054	-0 days -23:40:19.000000000	162312
# 4	8154	5503	-1 days -13:21:53.000000000	658844

# Запишите данные из файла в переменную df. Далее переведите delay в timedelta формат. Обратите внимание, что так просто столбец не переведётся – нужно будет убрать -.

# NB! Данные уже записаны в переменную df.

# Могут понадобиться:

# pd.to_timedelta()
# pd.Series.str

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Karpov/lesson_6/delays.csv')
df

df.delay = df.delay.str.replace('-', '')
df.delay = pd.to_timedelta(df.delay)

df['delay_categorical'] = pd.cut(df.delay, bins=3)

df

# 💀 Сложное задание! 💀
# Разбилось конечно неплохо, но хочется чуть более целые значения и более человеческие названия.
# В этом нам помогут аргументы функции pd.cut! Перезадайте колонку delay_categorical, чтобы значения в ней были:

# 'less than 1 day' – время от 0 до 1 дня
# '1-2 days' – от 1 до 2 дней
# '2-3 days' – от 2 до 3 дней
#  'more than 3 days' – больше 3 дней

bins = pd.to_timedelta(['0d', '1d', '2d', '3d', '10000d'])
labels = ['less than 1 day', '1-2 days','2-3 days', 'more than 3 days']
df['delay_categorical'] = pd.cut(df.delay, bins=bins, labels=labels)

# Прекрасно! Теперь постройте интерактивный барплот с тем, насколько часто задерживаются сделки.
# Отсортируйте варианты так, чтобы снизу был самый редкий, а сверху – самый частый.

ax = df.groupby('delay_categorical', as_index=False) \
  .agg({'revenue': 'count'}) \
  .rename(columns={'revenue': 'frq'}) \
  .sort_values('frq')
px.bar(x=ax.delay_categorical, y=ax.frq)

ax

ads_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Karpov/lesson_6/ads_data.csv', parse_dates=['date', 'time'])
ads_clients_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Karpov/lesson_6/ads_clients_data.csv', parse_dates=['create_date', 'date'])

# Посмотрим Na значения
ads_data.isna().sum()

ads_data

# Для начала посчитаем среднее количество разных рекламных событий (показы и клики) по объявлениям.
# Тонкий момент: помните, что некоторые показываемые объявления не кликались, и при группировке в таких случаях не будет строк с кликами, 
# а для подсчёта среднего по объявлениям их нужно учитывать. Округлите ответы до целых чисел.

# Всего объявлений
total_ads=ads_data.ad_id.nunique()

ads_data.groupby(['ad_id', 'event'], as_index=False) \
        .agg({'platform': 'count'}) \
        .rename(columns={'platform': 'count'}) \
        .pivot(index='ad_id', columns='event', values='count') \
        .fillna(0) \
        .mean() \
        .round()

# Давайте посмотрим на распределение показов объявлений!
  # По оси x – число показов
  # По оси y – доля объявлений с такими показами
# Прологарифмируйте число показов, а затем постройте такой график, чтобы можно было понять форму распределения. Выберите соответствующий график:

views = ads_data.groupby(['ad_id', 'event'], as_index=False) \
        .agg({'platform': 'count'}) \
        .rename(columns={'platform': 'count'}) \
        .pivot(index='ad_id', columns='event', values='count') \
        # .fillna(0)

views
log_views = np.log(views.view)

sns.distplot(log_views)

# Теперь нужно найти среднее количество показов на 1 объявление (ad_id) по дням,
# не учитывая объявления, у которых не было показов (обычное среднее).
# После этого посчитайте скользящее среднее по полученному результату с окном в 2 элемента.

# Вопрос: Какое значение скользящего среднего получим за 6 апреля 2019 года? Округлите ответ до целого числа.

average_views_by_day = ads_data.query('event == "view"')\
  .groupby('date', as_index=False) \
  .agg({'ad_id': 'nunique', 'event':'count'})\
  .rename(columns={'ad_id':'uniq_ads', 'event':'event_number'})

average_views_by_day['average'] = average_views_by_day.event_number / average_views_by_day.uniq_ads

average_views_by_day['rolling'] = average_views_by_day.average.rolling(2).mean()

average_views_by_day

# Здесь не нужно исхитряться как в 1-ом задании, так как нам не нужно учитывать объявления, у которых не было просмотров. 
# Отберите только просмотры, сгруппируйте данные по объявлениям и дням и посчитайте число просмотров для каждого объявления (`ad_id`) в каждый день (`date`). 
# После этого произведите группировку по дням и посчитайте среднее число просмотров для каждого дня. Потом посчитайте скользящее среднее с помощью `rolling`

# 2 вариант среднего
ads_data.query('event == "view"')\
  .groupby(['ad_id', 'date'], as_index=False)\
  .agg({'event':'count'})\
  .groupby('date')\
  .agg({'event':'mean'})\

# И еще 3 вариант среднего
ads_data.query('event == "view"')\
  .groupby(['date', 'ad_id']) \
  .agg({'event':'count'})\
  .groupby('date')\
  .agg({'event':'mean'})\

average_views_by_day.fillna(0)
average_views_by_day['diff'] = average_views_by_day['average'] - average_views_by_day['rolling']

average_views_by_day

# Ну а теперь найдём проблемное объявление (с наибольшим/наименьшим количеством показов) в день, 
# в который была замечена самая большая по модулю аномалия. 
# То есть нужно переиспользовать предыдущий датафрейм и найти среди данных рекламы в тот день объявление 
# с наибольшим или наименьшим числом показов.Потом напишите функцию, которая будет искать такое объявление в датасете.

# В ответе укажите id проблемного объявления в день, полученный на предыдущем шаге.

ads_data.query('event == "view" and date == "2019-04-06"')\
  .groupby('ad_id', as_index=False) \
  .agg({'event':'count'})\
  .sort_values('event')
  # .rename(columns={'ad_id':'uniq_ads', 'event':'event_number'})

# Объедините данные рекламы с данными о рекламных клиентах и найдите среднее количество дней от даты создания рекламного клиента (create_date)
#  и первым запуском рекламного объявления этим клиентом (date).

# В качестве ответа укажите среднее число дней.

ads_clients_data

ads = ads_data.merge(ads_clients_data, how='left', on='client_union_id')

ads.dtypes

ads['delta'] = ads['date_x'] - ads['create_date']
ads.head()

ads.groupby('client_union_id')\
  .agg({'delta':'min'})\
  .sort_values('delta')\
  .delta.mean()

# 💀 Сложное задание! 💀

# Давайте вычислим конверсию из создания рекламного кабинета в запуск первой рекламы в течение не более 365 дней.

# Конверсия – отношение числа клиентов, которые совершили целевое действие (создали рекламу), к общему числу клиентов.
# Например, 1000 клиентов создали кабинет, но лишь 50 из них запустили рекламу. В таком случае конверсия будет равна 5%

# Чтобы отобрать данные за нужный промежуток, можно воспользоваться сравнением времени до создания первой рекламы с pd.Timedelta(365, unit='day'))

# Ответ дайте в процентах и округлите до сотых. Пример ответа:

total_clients = ads.client_union_id.nunique()
total_clients

ads['less_year'] = ads.delta < '365d'
# pd.to_timedelta(ads.delta)

ads.query('less_year')

ads_clients_data.client_union_id.nunique()

total_clients / 122078*100

# Давайте разобъем наших клиентов по промежуткам от создания рекламного кабинета до запуска первого рекламного объявления.

# Определите, сколько уникальных клиентов запустили свое первое объявление в первый месяц своего существования (от 0 до 30 дней).
# Список промежутков дней для метода pd.cut() – [0, 30, 90, 180, 365]. Создать временные промежутки можно с помощью pd.to_timedelta().

ads.head()

bins_by_month = pd.to_timedelta(['0d', '30d', '90d', '180d', '365d'])
labels_by_month = ['less than moth', '1-3 month','4-6 month', '7-12 month']
ads['delay_by_month'] = pd.cut(ads.delta, bins=bins_by_month, labels=labels_by_month)

ads.query('delay_by_month == "less than moth"')\
  .groupby('client_union_id', as_index=False)\
  .agg({'event':'count'})\
  .shape

ads.groupby(['delay_by_month'], as_index=False)\
  .agg({'client_union_id':'nunique'})\
  .rename(columns={'client_union_id':'uniqs'})\
  .sort_values('uniqs')

